### ISSUE TITLE
Library?

### ISSUE THREAD

**Issue by stevesob** [cdellacqua/custom-uikit-svelte#1]
Any plans to make this a library?

How could the controls be added to an existing Svelte app?

**Comment by cdellacqua** [comment]
Hi, thanks for the interest.

Well, it is a library, but good observation, I'll add the installation instructions in the README 12765aaabd7a304915aac0c4633d42d570ab4e4d.
The project includes an App.svelte as a demo and as documentation with examples of some of the components it provides.

You can download it from [npm](https://www.npmjs.com/package/custom-uikit-svelte) (`npm i custom-uikit-svelte`) and include any component in the script tag of your own `.svelte` file, just like this:

```
<script>
  import { Button } from 'custom-uikit-svelte';
</script>

<Button>Click Me!</Button>
```

**Comment by stevesob** [comment]
Thanks for the reply and added instructions.

I am a long-time .Net developer and moving over to the world of Javascript,
frameworks, bundlers, etc is quite overwhelming.

How you guys figure all this out is truly amazing!
